# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TEST.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from PyQt5.QtGui import QPixmap
import sys, res, icons_rc
import MySQLdb
from classes.class_categorie import *
from classes.class_transmition import *
from classes.class_carburant import *
from classes.class_car import *
from classes.class_user import *
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1607, 634)
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("\n"
"\n"
"#centralwidget{\n"
"    background-color: #FFF5EE;\n"
"}\n"
"#tab{\n"
"color: white;\n"
"background-color:#FFF5EE;\n"
"}\n"
"#opBtn, #carBtn, #setBtn, #usrBtn{\n"
"border: 5px solid  #539CFF;\n"
"background-color:;\n"
"border-radius: 19px;\n"
"}\n"
"#opBtn:pressed{\n"
"    background-color: #539CFF;\n"
" }\n"
"#carBtn:pressed{\n"
"    background-color: #539CFF;\n"
" }\n"
"#setBtn:pressed{\n"
"    background-color: #539CFF;\n"
" }\n"
"#usrBtn:pressed{\n"
"    background-color: #539CFF;\n"
"  }\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.opBtn = QtWidgets.QPushButton(self.centralwidget)
        self.opBtn.setGeometry(QtCore.QRect(40, 100, 93, 81))
        self.opBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/rserv.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.opBtn.setIcon(icon)
        self.opBtn.setIconSize(QtCore.QSize(60, 70))
        self.opBtn.setObjectName("opBtn")
        self.carBtn = QtWidgets.QPushButton(self.centralwidget)
        self.carBtn.setGeometry(QtCore.QRect(40, 210, 93, 81))
        self.carBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/mn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.carBtn.setIcon(icon1)
        self.carBtn.setIconSize(QtCore.QSize(60, 60))
        self.carBtn.setObjectName("carBtn")
        self.usrBtn = QtWidgets.QPushButton(self.centralwidget)
        self.usrBtn.setGeometry(QtCore.QRect(40, 320, 93, 81))
        self.usrBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/prs.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.usrBtn.setIcon(icon2)
        self.usrBtn.setIconSize(QtCore.QSize(60, 60))
        self.usrBtn.setObjectName("usrBtn")
        self.setBtn = QtWidgets.QPushButton(self.centralwidget)
        self.setBtn.setGeometry(QtCore.QRect(40, 430, 93, 81))
        self.setBtn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/st.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setBtn.setIcon(icon3)
        self.setBtn.setIconSize(QtCore.QSize(60, 60))
        self.setBtn.setObjectName("setBtn")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(160, 10, 1451, 761))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(11)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("QPushButton#addOpBtn{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477,stop:0 rgba(0,131,120,219),stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#addOpBtn:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));}\n"
"QPushButton#addOpBtn:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"background-color:rgba(150, 123, 111,255);}\n"
"\n"
"\n"
"QPushButton#delOpBtn{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477,stop:0 rgba(150, 123, 111, 219),stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#delOpBtn:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111,255), stop:1 rgba(85, 81, 84, 226));}\n"
"QPushButton#delOpBtn:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"background-color:rgba(150, 123, 111,255);}\n"
"\n"
"QPushButton#updOpBtn{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477,stop:0 rgb(0, 156, 208),stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#updOpBtn:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111,255), stop:1 rgba(85, 81, 84, 226));}\n"
"QPushButton#updOpBtn:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"background-color:rgba(150, 123, 111,255);}\n"
"\n"
"QPushButton#addcBtn{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477,stop:0 rgba(0,131,120,219),stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#addcBtn:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));}\n"
"QPushButton#addcBtn:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"background-color:rgba(150, 123, 111,255);}\n"
"\n"
"QPushButton#delcBtn{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477,stop:0 rgba(150, 123, 111, 219),stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#delcBtn:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111,255), stop:1 rgba(85, 81, 84, 226));}\n"
"QPushButton#delcBtn:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"background-color:rgba(150, 123, 111,255);}\n"
"\n"
"QPushButton#editcBtn{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477,stop:0 rgb(0, 156, 208),stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#editcBtn:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111,255), stop:1 rgba(85, 81, 84, 226));}\n"
"QPushButton#editcBtn:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"background-color:rgba(150, 123, 111,255);}\n"
"\n"
"QPushButton#adduser{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477,stop:0 rgba(0,131,120,219),stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#adduser:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));}\n"
"QPushButton#adduser:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"background-color:rgba(150, 123, 111,255);}\n"
"\n"
"QPushButton#deluser{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477,stop:0 rgba(150, 123, 111, 219),stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#deluser:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111,255), stop:1 rgba(85, 81, 84, 226));}\n"
"QPushButton#deluser:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"background-color:rgba(150, 123, 111,255);}\n"
"\n"
"QPushButton#edituser{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477,stop:0 rgb(0, 156, 208),stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#edituser:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111,255), stop:1 rgba(85, 81, 84, 226));}\n"
"QPushButton#edituser:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"background-color:rgba(150, 123, 111,255);}\n"
"\n"
"\n"
"\n"
"QPushButton#addcatBtn{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477,stop:0 rgba(0,131,120,219),stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#addcatBtn:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));}\n"
"QPushButton#addcatBtn:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"background-color:rgba(150, 123, 111,255);}\n"
"\n"
"QPushButton#delcat{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477,stop:0 rgba(150, 123, 111, 219),stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#delcat:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111,255), stop:1 rgba(85, 81, 84, 226));}\n"
"QPushButton#delcat:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"background-color:rgba(150, 123, 111,255);}\n"
"\n"
"QPushButton#editcatB{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477,stop:0 rgb(0, 156, 208),stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#editcatB:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111,255), stop:1 rgba(85, 81, 84, 226));}\n"
"QPushButton#editcatB:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"background-color:rgba(150, 123, 111,255);}\n"
"\n"
"\n"
"\n"
"\n"
"QPushButton#addt{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477,stop:0 rgba(0,131,120,219),stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#addt:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));}\n"
"QPushButton#addt:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"background-color:rgba(150, 123, 111,255);}\n"
"QPushButton#delt{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477,stop:0 rgba(150, 123, 111, 219),stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#delt:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111,255), stop:1 rgba(85, 81, 84, 226));}\n"
"QPushButton#delt:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"background-color:rgba(150, 123, 111,255);}\n"
"\n"
"QPushButton#editt{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477,stop:0 rgb(0, 156, 208),stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#editt:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111,255), stop:1 rgba(85, 81, 84, 226));}\n"
"QPushButton#editt:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"background-color:rgba(150, 123, 111,255);}\n"
"\n"
"\n"
"\n"
"QPushButton#addcarb{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477,stop:0 rgba(0,131,120,219),stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#addcarb:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));}\n"
"QPushButton#addcarb:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"background-color:rgba(150, 123, 111,255);}\n"
"QPushButton#delcarb{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477,stop:0 rgba(150, 123, 111, 219),stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#delcarb:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111,255), stop:1 rgba(85, 81, 84, 226));}\n"
"QPushButton#delcarb:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"background-color:rgba(150, 123, 111,255);}\n"
"\n"
"QPushButton#editcarb{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477,stop:0 rgb(0, 156, 208),stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#editcarb:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111,255), stop:1 rgba(85, 81, 84, 226));}\n"
"QPushButton#editcarb:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"background-color:rgba(150, 123, 111,255);}\n"
"\n"
"QPushButton#searchbtn_2{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477,stop:0 rgb(0, 156, 208),stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#searchbtn_2:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111,255), stop:1 rgba(85, 81, 84, 226));}\n"
"QPushButton#searchbtn_2:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"background-color:rgba(150, 123, 111,255);}")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setGeometry(QtCore.QRect(0, 140, 1451, 511))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(12)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 255, 255))
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        self.tableWidget.verticalHeader().setVisible(False)
        self.addOpBtn = QtWidgets.QPushButton(self.tab)
        self.addOpBtn.setGeometry(QtCore.QRect(810, 30, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.addOpBtn.setFont(font)
        self.addOpBtn.setObjectName("addOpBtn")
        self.idtxt = QtWidgets.QLineEdit(self.tab)
        self.idtxt.setGeometry(QtCore.QRect(160, 51, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.idtxt.setFont(font)
        self.idtxt.setObjectName("idtxt")
        self.comboBox = QtWidgets.QComboBox(self.tab)
        self.comboBox.setGeometry(QtCore.QRect(520, 39, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.nbdateCMB = QtWidgets.QComboBox(self.tab)
        self.nbdateCMB.setGeometry(QtCore.QRect(520, 90, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.nbdateCMB.setFont(font)
        self.nbdateCMB.setObjectName("nbdateCMB")
        self.nbdateCMB.addItem("")
        self.nbdateCMB.addItem("")
        self.nbdateCMB.addItem("")
        self.nbdateCMB.addItem("")
        self.nbdateCMB.addItem("")
        self.nbdateCMB.addItem("")
        self.nbdateCMB.addItem("")
        self.nbdateCMB.addItem("")
        self.nbdateCMB.addItem("")
        self.nbdateCMB.addItem("")
        self.nbdateCMB.addItem("")
        self.nbdateCMB.addItem("")
        self.nbdateCMB.addItem("")
        self.nbdateCMB.addItem("")
        self.nbdateCMB.addItem("")
        self.nbdateCMB.addItem("")
        self.nbdateCMB.addItem("")
        self.nbdateCMB.addItem("")
        self.nbdateCMB.addItem("")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(400, 40, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(400, 90, 55, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_33 = QtWidgets.QLabel(self.tab)
        self.label_33.setGeometry(QtCore.QRect(10, 60, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.delOpBtn = QtWidgets.QPushButton(self.tab)
        self.delOpBtn.setGeometry(QtCore.QRect(1030, 30, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.delOpBtn.setFont(font)
        self.delOpBtn.setObjectName("delOpBtn")
        self.label_34 = QtWidgets.QLabel(self.tab)
        self.label_34.setGeometry(QtCore.QRect(0, 0, 481, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 0, 1451, 651))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget_2.setFont(font)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.tab_9)
        self.tableWidget_4.setGeometry(QtCore.QRect(-5, 120, 1451, 501))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tableWidget_4.setFont(font)
        self.tableWidget_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableWidget_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget_4.setLineWidth(2)
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(10)
        self.tableWidget_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(9, item)
        self.tableWidget_4.verticalHeader().setVisible(False)
        self.searchbtn_2 = QtWidgets.QPushButton(self.tab_9)
        self.searchbtn_2.setGeometry(QtCore.QRect(920, 60, 171, 51))
        self.searchbtn_2.setObjectName("searchbtn_2")
        self.searchtxt_2 = QtWidgets.QLineEdit(self.tab_9)
        self.searchtxt_2.setGeometry(QtCore.QRect(870, 20, 271, 31))
        self.searchtxt_2.setObjectName("searchtxt_2")
        self.searchCMB_2 = QtWidgets.QComboBox(self.tab_9)
        self.searchCMB_2.setGeometry(QtCore.QRect(260, 60, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.searchCMB_2.setFont(font)
        self.searchCMB_2.setObjectName("searchCMB_2")
        self.searchCMB_2.addItem("")
        self.searchCMB_2.addItem("")
        self.searchCMB_2.addItem("")
        self.searchCMB_2.addItem("")
        self.searchCMB_2.addItem("")
        self.label_36 = QtWidgets.QLabel(self.tab_9)
        self.label_36.setGeometry(QtCore.QRect(450, 20, 411, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.tab_9)
        self.label_37.setGeometry(QtCore.QRect(160, 60, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.tabWidget_2.addTab(self.tab_9, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.nbPlacetxt = QtWidgets.QLineEdit(self.tab_5)
        self.nbPlacetxt.setGeometry(QtCore.QRect(180, 200, 301, 31))
        self.nbPlacetxt.setObjectName("nbPlacetxt")
        self.modeletxt = QtWidgets.QLineEdit(self.tab_5)
        self.modeletxt.setGeometry(QtCore.QRect(180, 150, 301, 31))
        self.modeletxt.setObjectName("modeletxt")
        self.imagetxt = QtWidgets.QLineEdit(self.tab_5)
        self.imagetxt.setGeometry(QtCore.QRect(180, 301, 301, 31))
        self.imagetxt.setObjectName("imagetxt")
        self.marquetxt = QtWidgets.QLineEdit(self.tab_5)
        self.marquetxt.setGeometry(QtCore.QRect(180, 100, 301, 31))
        self.marquetxt.setObjectName("marquetxt")
        self.prixJourtxt = QtWidgets.QLineEdit(self.tab_5)
        self.prixJourtxt.setGeometry(QtCore.QRect(180, 250, 301, 31))
        self.prixJourtxt.setObjectName("prixJourtxt")
        self.categorieCMB = QtWidgets.QComboBox(self.tab_5)
        self.categorieCMB.setGeometry(QtCore.QRect(740, 100, 251, 31))
        self.categorieCMB.setObjectName("categorieCMB")
        self.carburantCMB = QtWidgets.QComboBox(self.tab_5)
        self.carburantCMB.setGeometry(QtCore.QRect(740, 160, 251, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        self.carburantCMB.setFont(font)
        self.carburantCMB.setObjectName("carburantCMB")
        self.dispoCMB = QtWidgets.QComboBox(self.tab_5)
        self.dispoCMB.setGeometry(QtCore.QRect(740, 220, 251, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        self.dispoCMB.setFont(font)
        self.dispoCMB.setObjectName("dispoCMB")
        self.transmitionCMB = QtWidgets.QComboBox(self.tab_5)
        self.transmitionCMB.setGeometry(QtCore.QRect(740, 280, 251, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        self.transmitionCMB.setFont(font)
        self.transmitionCMB.setObjectName("transmitionCMB")
        self.addcBtn = QtWidgets.QPushButton(self.tab_5)
        self.addcBtn.setGeometry(QtCore.QRect(460, 400, 171, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        self.addcBtn.setFont(font)
        self.addcBtn.setObjectName("addcBtn")
        self.label_3 = QtWidgets.QLabel(self.tab_5)
        self.label_3.setGeometry(QtCore.QRect(20, 100, 101, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab_5)
        self.label_4.setGeometry(QtCore.QRect(20, 150, 101, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab_5)
        self.label_5.setGeometry(QtCore.QRect(20, 200, 161, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab_5)
        self.label_6.setGeometry(QtCore.QRect(20, 250, 141, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab_5)
        self.label_7.setGeometry(QtCore.QRect(570, 110, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab_5)
        self.label_8.setGeometry(QtCore.QRect(570, 170, 151, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab_5)
        self.label_9.setGeometry(QtCore.QRect(20, 300, 111, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab_5)
        self.label_10.setGeometry(QtCore.QRect(570, 290, 141, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab_5)
        self.label_11.setGeometry(QtCore.QRect(570, 230, 141, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.label_12 = QtWidgets.QLabel(self.tab_6)
        self.label_12.setGeometry(QtCore.QRect(580, 140, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.editcarburantc = QtWidgets.QComboBox(self.tab_6)
        self.editcarburantc.setGeometry(QtCore.QRect(750, 190, 231, 31))
        self.editcarburantc.setObjectName("editcarburantc")
        self.editenbP = QtWidgets.QLineEdit(self.tab_6)
        self.editenbP.setGeometry(QtCore.QRect(180, 240, 301, 31))
        self.editenbP.setObjectName("editenbP")
        self.label_14 = QtWidgets.QLabel(self.tab_6)
        self.label_14.setGeometry(QtCore.QRect(580, 300, 131, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tab_6)
        self.label_15.setGeometry(QtCore.QRect(20, 190, 101, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.edittransmitionC = QtWidgets.QComboBox(self.tab_6)
        self.edittransmitionC.setGeometry(QtCore.QRect(750, 290, 231, 31))
        self.edittransmitionC.setObjectName("edittransmitionC")
        self.label_16 = QtWidgets.QLabel(self.tab_6)
        self.label_16.setGeometry(QtCore.QRect(20, 290, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.editdispoC = QtWidgets.QComboBox(self.tab_6)
        self.editdispoC.setGeometry(QtCore.QRect(750, 240, 231, 31))
        self.editdispoC.setObjectName("editdispoC")
        self.label_17 = QtWidgets.QLabel(self.tab_6)
        self.label_17.setGeometry(QtCore.QRect(20, 240, 151, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.tab_6)
        self.label_18.setGeometry(QtCore.QRect(20, 140, 101, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.editmarque = QtWidgets.QLineEdit(self.tab_6)
        self.editmarque.setGeometry(QtCore.QRect(180, 140, 301, 31))
        self.editmarque.setObjectName("editmarque")
        self.editmodele = QtWidgets.QLineEdit(self.tab_6)
        self.editmodele.setGeometry(QtCore.QRect(180, 190, 301, 31))
        self.editmodele.setObjectName("editmodele")
        self.label_19 = QtWidgets.QLabel(self.tab_6)
        self.label_19.setGeometry(QtCore.QRect(580, 250, 121, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.editcategorieC = QtWidgets.QComboBox(self.tab_6)
        self.editcategorieC.setGeometry(QtCore.QRect(750, 140, 231, 31))
        self.editcategorieC.setObjectName("editcategorieC")
        self.label_20 = QtWidgets.QLabel(self.tab_6)
        self.label_20.setGeometry(QtCore.QRect(580, 190, 151, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.editprix = QtWidgets.QLineEdit(self.tab_6)
        self.editprix.setGeometry(QtCore.QRect(180, 290, 301, 31))
        self.editprix.setObjectName("editprix")
        self.editcBtn = QtWidgets.QPushButton(self.tab_6)
        self.editcBtn.setGeometry(QtCore.QRect(830, 400, 171, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.editcBtn.setFont(font)
        self.editcBtn.setObjectName("editcBtn")
        self.editid = QtWidgets.QLineEdit(self.tab_6)
        self.editid.setGeometry(QtCore.QRect(560, 50, 301, 31))
        self.editid.setObjectName("editid")
        self.label_21 = QtWidgets.QLabel(self.tab_6)
        self.label_21.setGeometry(QtCore.QRect(480, 50, 61, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.delcBtn = QtWidgets.QPushButton(self.tab_6)
        self.delcBtn.setGeometry(QtCore.QRect(570, 400, 171, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.delcBtn.setFont(font)
        self.delcBtn.setObjectName("delcBtn")
        self.label_32 = QtWidgets.QLabel(self.tab_6)
        self.label_32.setGeometry(QtCore.QRect(20, 339, 111, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.editimage = QtWidgets.QLineEdit(self.tab_6)
        self.editimage.setGeometry(QtCore.QRect(180, 340, 301, 31))
        self.editimage.setObjectName("editimage")
        self.tabWidget_2.addTab(self.tab_6, "")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox.setGeometry(QtCore.QRect(0, 40, 461, 491))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(10, 110, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_22 = QtWidgets.QLabel(self.groupBox)
        self.label_22.setGeometry(QtCore.QRect(10, 160, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.groupBox)
        self.label_23.setGeometry(QtCore.QRect(10, 210, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.groupBox)
        self.label_24.setGeometry(QtCore.QRect(10, 260, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.username = QtWidgets.QLineEdit(self.groupBox)
        self.username.setGeometry(QtCore.QRect(150, 110, 231, 31))
        self.username.setObjectName("username")
        self.email = QtWidgets.QLineEdit(self.groupBox)
        self.email.setGeometry(QtCore.QRect(150, 160, 231, 31))
        self.email.setObjectName("email")
        self.passw = QtWidgets.QLineEdit(self.groupBox)
        self.passw.setGeometry(QtCore.QRect(150, 210, 231, 31))
        self.passw.setText("")
        self.passw.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passw.setObjectName("passw")
        self.confirmpass = QtWidgets.QLineEdit(self.groupBox)
        self.confirmpass.setGeometry(QtCore.QRect(150, 260, 231, 31))
        self.confirmpass.setText("")
        self.confirmpass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confirmpass.setObjectName("confirmpass")
        self.adduser = QtWidgets.QPushButton(self.groupBox)
        self.adduser.setGeometry(QtCore.QRect(140, 340, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.adduser.setFont(font)
        self.adduser.setObjectName("adduser")
        self.error = QtWidgets.QLabel(self.groupBox)
        self.error.setGeometry(QtCore.QRect(80, 430, 301, 20))
        self.error.setText("")
        self.error.setObjectName("error")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_2.setGeometry(QtCore.QRect(950, 40, 491, 491))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.newname = QtWidgets.QLineEdit(self.groupBox_2)
        self.newname.setGeometry(QtCore.QRect(200, 180, 231, 31))
        self.newname.setObjectName("newname")
        self.confpass = QtWidgets.QLineEdit(self.groupBox_2)
        self.confpass.setGeometry(QtCore.QRect(200, 330, 231, 31))
        self.confpass.setText("")
        self.confpass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confpass.setObjectName("confpass")
        self.label_26 = QtWidgets.QLabel(self.groupBox_2)
        self.label_26.setGeometry(QtCore.QRect(30, 230, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.newpass = QtWidgets.QLineEdit(self.groupBox_2)
        self.newpass.setGeometry(QtCore.QRect(200, 280, 231, 31))
        self.newpass.setText("")
        self.newpass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.newpass.setObjectName("newpass")
        self.edituser = QtWidgets.QPushButton(self.groupBox_2)
        self.edituser.setGeometry(QtCore.QRect(40, 400, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.edituser.setFont(font)
        self.edituser.setObjectName("edituser")
        self.label_27 = QtWidgets.QLabel(self.groupBox_2)
        self.label_27.setGeometry(QtCore.QRect(30, 180, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.groupBox_2)
        self.label_28.setGeometry(QtCore.QRect(30, 330, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.newemail = QtWidgets.QLineEdit(self.groupBox_2)
        self.newemail.setGeometry(QtCore.QRect(200, 230, 231, 31))
        self.newemail.setObjectName("newemail")
        self.label_25 = QtWidgets.QLabel(self.groupBox_2)
        self.label_25.setGeometry(QtCore.QRect(30, 280, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.oldname = QtWidgets.QLineEdit(self.groupBox_2)
        self.oldname.setGeometry(QtCore.QRect(170, 90, 201, 31))
        self.oldname.setObjectName("oldname")
        self.deluser = QtWidgets.QPushButton(self.groupBox_2)
        self.deluser.setGeometry(QtCore.QRect(260, 400, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.deluser.setFont(font)
        self.deluser.setObjectName("deluser")
        self.label_41 = QtWidgets.QLabel(self.groupBox_2)
        self.label_41.setGeometry(QtCore.QRect(70, 90, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.tableWidget_5 = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_5.setGeometry(QtCore.QRect(460, 170, 491, 361))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tableWidget_5.setFont(font)
        self.tableWidget_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableWidget_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget_5.setLineWidth(2)
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.setColumnCount(3)
        self.tableWidget_5.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(2, item)
        self.tableWidget_5.verticalHeader().setVisible(False)
        self.label_35 = QtWidgets.QLabel(self.tab_3)
        self.label_35.setGeometry(QtCore.QRect(590, 100, 201, 20))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.tab_4)
        self.tabWidget_3.setGeometry(QtCore.QRect(-4, 0, 1451, 731))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget_3.setFont(font)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_7)
        self.tableWidget_2.setGeometry(QtCore.QRect(-5, 150, 1451, 551))
        self.tableWidget_2.setMinimumSize(QtCore.QSize(20, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tableWidget_2.setFont(font)
        self.tableWidget_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget_2.setAutoScrollMargin(20)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(2)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        self.tableWidget_2.horizontalHeader().setMinimumSectionSize(60)
        self.tableWidget_2.verticalHeader().setVisible(False)
        self.tableWidget_2.verticalHeader().setDefaultSectionSize(40)
        self.label_29 = QtWidgets.QLabel(self.tab_7)
        self.label_29.setGeometry(QtCore.QRect(10, 20, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.addcatBtn = QtWidgets.QPushButton(self.tab_7)
        self.addcatBtn.setGeometry(QtCore.QRect(370, 90, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.addcatBtn.setFont(font)
        self.addcatBtn.setObjectName("addcatBtn")
        self.categorietxt = QtWidgets.QLineEdit(self.tab_7)
        self.categorietxt.setGeometry(QtCore.QRect(70, 50, 291, 31))
        self.categorietxt.setObjectName("categorietxt")
        self.delcat = QtWidgets.QPushButton(self.tab_7)
        self.delcat.setGeometry(QtCore.QRect(1200, 50, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.delcat.setFont(font)
        self.delcat.setObjectName("delcat")
        self.editcatB = QtWidgets.QPushButton(self.tab_7)
        self.editcatB.setGeometry(QtCore.QRect(940, 50, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.editcatB.setFont(font)
        self.editcatB.setObjectName("editcatB")
        self.categorieid = QtWidgets.QLineEdit(self.tab_7)
        self.categorieid.setGeometry(QtCore.QRect(600, 50, 291, 31))
        self.categorieid.setObjectName("categorieid")
        self.label_31 = QtWidgets.QLabel(self.tab_7)
        self.label_31.setGeometry(QtCore.QRect(520, 20, 361, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.tabWidget_3.addTab(self.tab_7, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.label_38 = QtWidgets.QLabel(self.tab_10)
        self.label_38.setGeometry(QtCore.QRect(10, 20, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.transmitionid = QtWidgets.QLineEdit(self.tab_10)
        self.transmitionid.setGeometry(QtCore.QRect(600, 50, 291, 31))
        self.transmitionid.setObjectName("transmitionid")
        self.editt = QtWidgets.QPushButton(self.tab_10)
        self.editt.setGeometry(QtCore.QRect(950, 50, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.editt.setFont(font)
        self.editt.setObjectName("editt")
        self.addt = QtWidgets.QPushButton(self.tab_10)
        self.addt.setGeometry(QtCore.QRect(370, 90, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.addt.setFont(font)
        self.addt.setObjectName("addt")
        self.delt = QtWidgets.QPushButton(self.tab_10)
        self.delt.setGeometry(QtCore.QRect(1200, 50, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.delt.setFont(font)
        self.delt.setObjectName("delt")
        self.transmition = QtWidgets.QLineEdit(self.tab_10)
        self.transmition.setGeometry(QtCore.QRect(70, 50, 291, 31))
        self.transmition.setObjectName("transmition")
        self.tableWidget_7 = QtWidgets.QTableWidget(self.tab_10)
        self.tableWidget_7.setGeometry(QtCore.QRect(-5, 150, 1451, 551))
        self.tableWidget_7.setMinimumSize(QtCore.QSize(20, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tableWidget_7.setFont(font)
        self.tableWidget_7.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget_7.setAutoScrollMargin(20)
        self.tableWidget_7.setObjectName("tableWidget_7")
        self.tableWidget_7.setColumnCount(2)
        self.tableWidget_7.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(1, item)
        self.tableWidget_7.horizontalHeader().setMinimumSectionSize(60)
        self.tableWidget_7.verticalHeader().setVisible(False)
        self.tableWidget_7.verticalHeader().setDefaultSectionSize(40)
        self.label_39 = QtWidgets.QLabel(self.tab_10)
        self.label_39.setGeometry(QtCore.QRect(520, 20, 361, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.tabWidget_3.addTab(self.tab_10, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.label_40 = QtWidgets.QLabel(self.tab_8)
        self.label_40.setGeometry(QtCore.QRect(520, 20, 391, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.delcarb = QtWidgets.QPushButton(self.tab_8)
        self.delcarb.setGeometry(QtCore.QRect(1170, 50, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.delcarb.setFont(font)
        self.delcarb.setObjectName("delcarb")
        self.label_30 = QtWidgets.QLabel(self.tab_8)
        self.label_30.setGeometry(QtCore.QRect(10, 20, 311, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tab_8)
        self.tableWidget_3.setGeometry(QtCore.QRect(0, 150, 1461, 551))
        self.tableWidget_3.setMinimumSize(QtCore.QSize(20, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tableWidget_3.setFont(font)
        self.tableWidget_3.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget_3.setAutoScrollMargin(20)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(2)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        self.tableWidget_3.horizontalHeader().setMinimumSectionSize(60)
        self.tableWidget_3.verticalHeader().setVisible(False)
        self.tableWidget_3.verticalHeader().setDefaultSectionSize(40)
        self.editcarb = QtWidgets.QPushButton(self.tab_8)
        self.editcarb.setGeometry(QtCore.QRect(940, 50, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.editcarb.setFont(font)
        self.editcarb.setObjectName("editcarb")
        self.addcarb = QtWidgets.QPushButton(self.tab_8)
        self.addcarb.setGeometry(QtCore.QRect(370, 90, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.addcarb.setFont(font)
        self.addcarb.setObjectName("addcarb")
        self.carburantid = QtWidgets.QLineEdit(self.tab_8)
        self.carburantid.setGeometry(QtCore.QRect(600, 50, 291, 31))
        self.carburantid.setObjectName("carburantid")
        self.carburant = QtWidgets.QLineEdit(self.tab_8)
        self.carburant.setGeometry(QtCore.QRect(70, 50, 291, 31))
        self.carburant.setObjectName("carburant")
        self.tabWidget_3.addTab(self.tab_8, "")
        self.tabWidget.addTab(self.tab_4, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1607, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Image"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Marque"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Model"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Categorie"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "TypeCarburant"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "NombrePlace"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Transmission"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "PrixParJour"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "dateReservation"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "dateLimite"))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "Client email"))
        self.addOpBtn.setText(_translate("MainWindow", "Add"))
        self.nbdateCMB.setItemText(0, _translate("MainWindow", "1"))
        self.nbdateCMB.setItemText(1, _translate("MainWindow", "2"))
        self.nbdateCMB.setItemText(2, _translate("MainWindow", "3"))
        self.nbdateCMB.setItemText(3, _translate("MainWindow", "4"))
        self.nbdateCMB.setItemText(4, _translate("MainWindow", "5"))
        self.nbdateCMB.setItemText(5, _translate("MainWindow", "6"))
        self.nbdateCMB.setItemText(6, _translate("MainWindow", "7"))
        self.nbdateCMB.setItemText(7, _translate("MainWindow", "8"))
        self.nbdateCMB.setItemText(8, _translate("MainWindow", "9"))
        self.nbdateCMB.setItemText(9, _translate("MainWindow", "10"))
        self.nbdateCMB.setItemText(10, _translate("MainWindow", "11"))
        self.nbdateCMB.setItemText(11, _translate("MainWindow", "12"))
        self.nbdateCMB.setItemText(12, _translate("MainWindow", "13"))
        self.nbdateCMB.setItemText(13, _translate("MainWindow", "14"))
        self.nbdateCMB.setItemText(14, _translate("MainWindow", "15"))
        self.nbdateCMB.setItemText(15, _translate("MainWindow", "16"))
        self.nbdateCMB.setItemText(16, _translate("MainWindow", "17"))
        self.nbdateCMB.setItemText(17, _translate("MainWindow", "18"))
        self.nbdateCMB.setItemText(18, _translate("MainWindow", "19"))
        self.label.setText(_translate("MainWindow", "Disponibilite"))
        self.label_2.setText(_translate("MainWindow", "Days"))
        self.label_33.setText(_translate("MainWindow", "Id of the element"))
        self.delOpBtn.setText(_translate("MainWindow", "Reset"))
        self.label_34.setText(_translate("MainWindow", "Add cars that you have lent"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Current reservations"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Image"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Marque"))
        item = self.tableWidget_4.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Modele"))
        item = self.tableWidget_4.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Categorie"))
        item = self.tableWidget_4.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Type carburant"))
        item = self.tableWidget_4.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Nombre Place"))
        item = self.tableWidget_4.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Transmition"))
        item = self.tableWidget_4.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Prix"))
        item = self.tableWidget_4.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Disponibilite"))
        self.searchbtn_2.setText(_translate("MainWindow", "Search"))
        self.searchCMB_2.setItemText(0, _translate("MainWindow", "Marque"))
        self.searchCMB_2.setItemText(1, _translate("MainWindow", "Type de Carburant"))
        self.searchCMB_2.setItemText(2, _translate("MainWindow", "Nombre du Place"))
        self.searchCMB_2.setItemText(3, _translate("MainWindow", "Prix par jour"))
        self.searchCMB_2.setItemText(4, _translate("MainWindow", "Transmition"))
        self.label_36.setText(_translate("MainWindow", "search for the car you want and remember its id"))
        self.label_37.setText(_translate("MainWindow", "Search by :"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_9), _translate("MainWindow", "Available cars"))
        self.addcBtn.setText(_translate("MainWindow", "ADD car"))
        self.label_3.setText(_translate("MainWindow", "Marque"))
        self.label_4.setText(_translate("MainWindow", "Modele"))
        self.label_5.setText(_translate("MainWindow", "Nombre de Place"))
        self.label_6.setText(_translate("MainWindow", "Prix par Jour"))
        self.label_7.setText(_translate("MainWindow", "Categorie"))
        self.label_8.setText(_translate("MainWindow", "Type Carburant"))
        self.label_9.setText(_translate("MainWindow", "image url"))
        self.label_10.setText(_translate("MainWindow", "Transmition"))
        self.label_11.setText(_translate("MainWindow", "Disponibilite"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "Add new car"))
        self.label_12.setText(_translate("MainWindow", "Categorie"))
        self.label_14.setText(_translate("MainWindow", "Transmition"))
        self.label_15.setText(_translate("MainWindow", "Modele"))
        self.label_16.setText(_translate("MainWindow", "Prix par Jour"))
        self.label_17.setText(_translate("MainWindow", "Nombre de Place"))
        self.label_18.setText(_translate("MainWindow", "Marque"))
        self.label_19.setText(_translate("MainWindow", "Disponibilite"))
        self.label_20.setText(_translate("MainWindow", "Type Carburant"))
        self.editcBtn.setText(_translate("MainWindow", "Edit"))
        self.label_21.setText(_translate("MainWindow", "car ID"))
        self.delcBtn.setText(_translate("MainWindow", "Delete"))
        self.label_32.setText(_translate("MainWindow", "image url"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "Edit or Delete car"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Add or Edit cars"))
        self.groupBox.setTitle(_translate("MainWindow", "Add new user"))
        self.label_13.setText(_translate("MainWindow", "user name"))
        self.label_22.setText(_translate("MainWindow", "email"))
        self.label_23.setText(_translate("MainWindow", "password"))
        self.label_24.setText(_translate("MainWindow", "confirm password"))
        self.adduser.setText(_translate("MainWindow", "Add user"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Edit user information"))
        self.label_26.setText(_translate("MainWindow", "email"))
        self.edituser.setText(_translate("MainWindow", "Edit user info"))
        self.label_27.setText(_translate("MainWindow", "new name"))
        self.label_28.setText(_translate("MainWindow", "confirm password"))
        self.label_25.setText(_translate("MainWindow", "password"))
        self.deluser.setText(_translate("MainWindow", "Delete user"))
        self.label_41.setText(_translate("MainWindow", "user name"))
        item = self.tableWidget_5.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "user name"))
        item = self.tableWidget_5.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "email"))
        item = self.tableWidget_5.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "type"))
        self.label_35.setText(_translate("MainWindow", "USERS ACCOUNTS"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Users"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "id Category"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Category Name"))
        self.label_29.setText(_translate("MainWindow", "New Categorie Name"))
        self.addcatBtn.setText(_translate("MainWindow", "ADD new categorie"))
        self.delcat.setText(_translate("MainWindow", "DELETE"))
        self.editcatB.setText(_translate("MainWindow", "EDIT"))
        self.label_31.setText(_translate("MainWindow", "Change  or delete categorie by id"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_7), _translate("MainWindow", "Categories"))
        self.label_38.setText(_translate("MainWindow", "New transmition Name"))
        self.editt.setText(_translate("MainWindow", "EDIT"))
        self.addt.setText(_translate("MainWindow", "ADD new transmition"))
        self.delt.setText(_translate("MainWindow", "DELETE"))
        item = self.tableWidget_7.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "id Transmition"))
        item = self.tableWidget_7.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Transmition Name"))
        self.label_39.setText(_translate("MainWindow", "Change or delete transmition by id"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_10), _translate("MainWindow", "Transmition"))
        self.label_40.setText(_translate("MainWindow", "Change or delete carburant type by id"))
        self.delcarb.setText(_translate("MainWindow", "DELETE"))
        self.label_30.setText(_translate("MainWindow", "New carburant type Name"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "id Carburant"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "carburant Type"))
        self.editcarb.setText(_translate("MainWindow", "EDIT"))
        self.addcarb.setText(_translate("MainWindow", "ADD new categorie"))
        self.addcarb.setText(_translate("MainWindow", "ADD new carburant"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_8), _translate("MainWindow", "Carburant"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Settings"))
      

        


        self.Handel_Buttons()
        self.Handel_UI_Changes()
        self.Show_categorie()
        self.Show_categorie_cmb()
        self.Show_carburant_cmb()
        self.Show_disponibiliter_cmb()
        self.Show_transmition_cmb()
        self.Show_car()
        self.Show_user()
        self.Show_Opcar()
        self.Show_transmition()
        self.Show_carburant()




    def Handel_UI_Changes(self):
        self.tabWidget.tabBar().setVisible(False)

    def Handel_Buttons(self):
        self.opBtn.clicked.connect(self.operations_show)
        self.carBtn.clicked.connect(self.cars_show)
        self.usrBtn.clicked.connect(self.user_show)
        self.setBtn.clicked.connect(self.settings_show)
        self.addcBtn.clicked.connect(self.Add_car)
        self.addOpBtn.clicked.connect(self.Add_carOp)
        self.delOpBtn.clicked.connect(self.Delete_carOp)
        self.editcBtn.clicked.connect(self.Edit_car)
        self.searchbtn_2.clicked.connect(self.Search_car)
        self.delcBtn.clicked.connect(self.Delete_car) 

        self.adduser.clicked.connect(self.Add_user)
        self.edituser.clicked.connect(self.Edit_user)
        self.deluser.clicked.connect(self.Delete_user)

        self.addcatBtn.clicked.connect(self.Add_categorie)
        self.delcat.clicked.connect(self.Delete_categorie)
        self.editcatB.clicked.connect(self.Edit_categorie)
        self.addcarb.clicked.connect(self.Add_carburant)
        self.delcarb.clicked.connect(self.Delete_carburant)
        self.editcarb.clicked.connect(self.Edit_carburant)
        self.addt.clicked.connect(self.Add_transmition)
        self.delt.clicked.connect(self.Delete_transmition)
        self.editt.clicked.connect(self.Edit_transmition)

        


        ##############################################
        #######tabs opener ###########################

    def operations_show(self):
         self.tabWidget.setCurrentIndex(0)

    def cars_show(self):
         self.tabWidget.setCurrentIndex(1)

    def user_show(self):
         self.tabWidget.setCurrentIndex(2)

    def settings_show(self):
         self.tabWidget.setCurrentIndex(3)


         ##############################################
         ######cars ###################################

    def Add_car(self):
        
        car_id = self.idtxt.text()
        car_marque = self.marquetxt.text()
        car_modele = self.modeletxt.text()
        car_image = self.imagetxt.text()
        car_nbPlace = self.nbPlacetxt.text()
        car_prix = self.prixJourtxt.text()
        car_categorie = self.categorieCMB.currentText()
        car_carburant = self.carburantCMB.currentText()
        car_disponibilite = self.dispoCMB.currentText()
        car_transmition = self.transmitionCMB.currentText()
        car_dispoCHange = self.comboBox.currentText()
        car_date = self.nbdateCMB.currentText()


        addCar = Cars(car_id, car_marque, car_modele, car_image, car_nbPlace, car_carburant, car_categorie, car_transmition, car_prix, car_disponibilite, car_dispoCHange, car_date)
        add = addCar.AddC()
        self.marquetxt.setText('')
        self.modeletxt.setText('')
        self.imagetxt.setText('')
        self.nbPlacetxt.setText('')
        self.prixJourtxt.setText('')
        self.Show_Opcar()
        self.Show_car()

    def Show_Opcar(self):
        self.db = MySQLdb.connect(host='localhost' ,user='root' ,password='Houssam@2002' ,db='carrental')
        self.cur= self.db.cursor()
        self.cur.execute('''SELECT idC, image, marque, modele,  categorie, typeCarburant, nombrePlace, transmition, prixJour, dateReserv, dateRetrieve from car where Disponibilite = "Non Disponible"''')
        data = self.cur.fetchall()


        if data :
            self.tableWidget.setRowCount(0)
            self.tableWidget.insertRow(0)
            for row , form in enumerate(data) :
                for column , item in enumerate(form) :
                
                    if (column == 1):
                        pixmap = QPixmap()
                        pixmap.loadFromData(item)
                        QTableWidgetItem(str(item)).setIcon(QIcon(pixmap))
                    else:   
                        self.tableWidget.setItem(row , column , QTableWidgetItem(str(item)))
                        column += 1

                
                row_position = self.tableWidget.rowCount()
                self.tableWidget.insertRow(row_position)

    def Show_car(self):
        self.db = MySQLdb.connect(host='localhost' ,user='root' ,password='Houssam@2002' ,db='carrental')
        self.cur= self.db.cursor()
        self.cur.execute('''SELECT idC, image, marque, modele,  categorie, typeCarburant, nombrePlace, transmition, prixJour, Disponibilite from car ''')
        data = self.cur.fetchall()


        if data :
            self.tableWidget_4.setRowCount(0)
            self.tableWidget_4.insertRow(0)
            for row , form in enumerate(data) :
                for column , item in enumerate(form) :
                    it = str(item)
                    if (column == 1):
                        it=self.getImageLabel(item)
                        self.tableWidget_4.setCellWidget(row, column, it)
                    else:   
                        self.tableWidget_4.setItem(row , column , QTableWidgetItem(str(item)))
                        column += 1

                
                row_position = self.tableWidget_4.rowCount()
                self.tableWidget_4.insertRow(row_position)
    def getImageLabel(self,image):
                imageLabel = QLabel(self.centralwidget)
                imageLabel.setText("")
                imageLabel.setScaledContents(True)
                pixmap = QPixmap()
                pixmap.loadFromData(image, '.jpg')
                imageLabel.setPixmap(pixmap)
                return imageLabel
    

    def Add_carOp(self):
        
        
        car_id = self.idtxt.text()
        car_dispoCHange = self.comboBox.currentText()
        car_date = self.nbdateCMB.currentText()
        addCarOP = Cars(car_id, '', '', '', '', '', '', '', '','', car_dispoCHange,car_date)
        add = addCarOP.AddCO()
        self.idtxt.setText('')
        self.Show_Opcar()
        self.Show_car()

    def Delete_carOp(self):
    
        car_id = self.idtxt.text()
        car_dispoCHange = self.comboBox.currentText()
        deleteCarOP = Cars(car_id, '', '', '', '', '', '', '', '', car_dispoCHange,'')
        delete = deleteCarOP.DeleteCO()
        self.idtxt.setText('')
        self.Show_Opcar()
        self.Show_car()
        
    def Search_car(self):
        self.db = MySQLdb.connect(host='localhost' ,user='root' ,password='Houssam@2002' ,db='carrental')
        self.cur= self.db.cursor()
        search = self.searchtxt_2.text()
        searchBy = self.searchCMB_2.currentText()
        if(searchBy == 'Marque'):
            self.cur.execute('''SELECT idC, image, marque, modele,  categorie, typeCarburant, nombrePlace, transmition, prixJour, Disponibilite from car where marque = (%s)''',(search,))
            
        elif(searchBy == 'Type de Carburant'):
            self.cur.execute('''SELECT idC, image, marque, modele,  categorie, typeCarburant, nombrePlace, transmition, prixJour, Disponibilite from car  where typeCarburant = (%s)''',(search,))
           
        elif(searchBy == 'Nombre du Place'):
            self.cur.execute('''SELECT idC, image, marque, modele,  categorie, typeCarburant, nombrePlace, transmition, prixJour, Disponibilite from car  where nombrePlace = (%s)''',(search,))
            
        elif(searchBy == 'Prix par jour'):
            self.cur.execute('''SELECT idC, image, marque, modele,  categorie, typeCarburant, nombrePlace, transmition, prixJour, Disponibilite from car  where prixJour = (%s)''',(search,))
            
        elif(searchBy == 'Transmition'):
            self.cur.execute('''SELECT idC, image, marque, modele,  categorie, typeCarburant, nombrePlace, transmition, prixJour, Disponibilite from car  where transmition = (%s)''',(search,))
            
        data = self.cur.fetchall()
        if data :
            self.tableWidget_4.setRowCount(0)
            self.tableWidget_4.insertRow(0)
            for row , form in enumerate(data) :
                for column , item in enumerate(form) :
                    it = str(item)
                    if (column == 1):
                        it=self.getImageLabel(item)
                        self.tableWidget_4.setCellWidget(row, column, it)
                    else:   
                        self.tableWidget_4.setItem(row , column , QTableWidgetItem(str(item)))
                        column += 1

                
                row_position = self.tableWidget_4.rowCount()
                self.tableWidget_4.insertRow(row_position)
        self.searchtxt_2.setText('')
    def Edit_car(self):
        car_id= self.editid.text()
        car_marque = self.editmarque.text()
        car_modele = self.editmodele.text()
        car_image = self.editimage.text()
        car_nbPlace = self.editenbP.text()
        car_prix = self.editprix.text()
        car_categorie = self.editcategorieC.currentText()
        car_carburant = self.editcarburantc.currentText()
        car_disponibilite = self.editdispoC.currentText()
        car_transmition = self.edittransmitionC.currentText()

        

        editCar = Cars(car_id, car_marque, car_modele, car_image, car_nbPlace, car_carburant, car_categorie, car_transmition, car_prix, car_disponibilite, '', '')
        edit = editCar.EditC()
        self.editid.setText('')
        self.editmarque.setText('')
        self.editmodele.setText('')
        self.editimage.setText('')
        self.editprix.setText('')
        self.editenbP.setText('')
        self.Show_Opcar()
        self.Show_car()

    def Delete_car(self):
       
        car_id= self.editid.text()
       

        deleteCar = Cars(car_id,'','','','','','','','','','','')
        delete = deleteCar.DeleteC()
        self.editid.setText('')
        self.Show_Opcar()
        self.Show_car()

         ###############################################
         ######users ###################################

    def Add_user(self):
        

        Uname = self.username.text()
        email = self.email.text()
        password = self.passw.text()
        cpass = self.confirmpass.text()
        
        if password == cpass:
            adduser=Users(Uname, email, password,'')
            add=adduser.AddU()
            self.error.setText("user "+Uname+" added succefuly")
            self.username.setText('')
            self.email.setText('')
            self.passw.setText('')
            self.confirmpass.setText('')
            self.Show_user()
        else:
            self.error.setText("the password does not match")
            self.confirmpass.setText('')
            self.passw.setText('')
        

    def Edit_user(self):
        Oname = self.oldname.text()
        Uname = self.newname.text()
        email = self.newemail.text()
        password = self.newpass.text()
        cpass = self.confpass.text()
        
        if password == cpass:
            editUser=Users(Uname, email, password, Oname)
            edit=editUser.EditU()
            self.error.setText("user "+Uname+" was updated succefuly")
            self.oldname.setText('')
            self.newname.setText('')
            self.newemail.setText('')
            self.newpass.setText('')
            self.confpass.setText('')
            self.Show_user()
        else:
            self.error.setText("the password does not match")
            self.confpass.setText('')
            self.newpass.setText('')

    def Delete_user(self):
        Oname = self.oldname.text()
         
        deleteUser=Users('','','',Oname)
        delete=deleteUser.DeleteU()
        #self.error.setText("user "+Oname+" was deleted succefuly")
        self.oldname.setText('')
        self.Show_user()
      

    def Show_user(self):
        self.db = MySQLdb.connect(host='localhost' ,user='root' ,password='Houssam@2002' ,db='carrental')
        self.cur= self.db.cursor()
        self.cur.execute('''SELECT nomP, email, type from users''')
        data = self.cur.fetchall()


        if data :
            self.tableWidget_5.setRowCount(0)
            self.tableWidget_5.insertRow(0)
            for row , form in enumerate(data) :
                for column , item in enumerate(form) :
                    self.tableWidget_5.setItem(row , column , QTableWidgetItem(str(item)))
                    column += 1

                
                row_position = self.tableWidget_5.rowCount()
                self.tableWidget_5.insertRow(row_position)

        ###############################################
        ######settings ###################################

 #######categories 
    def Add_categorie(self):
        categorie_id = self.categorieid.text()
        categorie_name = self.categorietxt.text()
        addCat = Categories(categorie_id, categorie_name)
        add = addCat.AddC()
        self.categorietxt.setText('')
        self.Show_categorie()
        


    def Edit_categorie(self):
        categorie_name = self.categorietxt.text()
        categorie_id = self.categorieid.text()
        editCat = Categories(categorie_id, categorie_name)
        edit = editCat.EditC()
        self.categorietxt.setText('')
        self.categorieid.setText('')
        self.Show_categorie()

    
    def Delete_categorie(self):

        categorie_name = self.categorietxt.text()
        categorie_id = self.categorieid.text()
        deleteCat = Categories(categorie_id, categorie_name)
        delete = deleteCat.DeleteC()
        self.categorieid.setText('')
        self.Show_categorie()

    def Show_categorie(self):
        self.db = MySQLdb.connect(host='localhost' ,user='root' ,password='Houssam@2002' ,db='carrental')
        self.cur= self.db.cursor()
        self.cur.execute('''SELECT idCategorie, Cname from categorie ''')
        data = self.cur.fetchall()


        if data :
            self.tableWidget_2.setRowCount(0)
            self.tableWidget_2.insertRow(0)
            for row , form in enumerate(data) :
                for column , item in enumerate(form) :
                    self.tableWidget_2.setItem(row , column , QTableWidgetItem(str(item)))
                    column += 1

                
                row_position = self.tableWidget_2.rowCount()
                self.tableWidget_2.insertRow(row_position)

 ###########Transmition
    
    def Add_transmition(self):
        id_transmition= self.transmitionid.text()
        type_transmition= self.transmition.text()
        addTr = Transmitions(id_transmition, type_transmition)
        add = addTr.AddT()
        self.transmition.setText('')
        self.Show_transmition()

  

    def Edit_transmition(self):
        id_transmition= self.transmitionid.text()
        type_transmition= self.transmition.text()
        editTr = Transmitions(id_transmition, type_transmition)
        edit = editTr.Editt()
        self.transmition.setText('')
        self.transmitionid.setText('')
        self.Show_transmition()


    
    def Delete_transmition(self):
        id_transmition= self.transmitionid.text()
        type_transmition= self.transmition.text()
        deleteTr = Transmitions(id_transmition, type_transmition)
        delete = deleteTr.Deletet()
        self.transmition.setText('')
        self.transmitionid.setText('')
        self.Show_transmition()



    def Show_transmition(self):
        self.db = MySQLdb.connect(host='localhost' ,user='root' ,password='Houssam@2002' ,db='carrental')
        self.cur= self.db.cursor()
        self.cur.execute('''SELECT idT, typeTransmition from transmition ''')
        data = self.cur.fetchall()


        if data :
            self.tableWidget_7.setRowCount(0)
            self.tableWidget_7.insertRow(0)
            for row , form in enumerate(data) :
                for column , item in enumerate(form) :
                    self.tableWidget_7.setItem(row , column , QTableWidgetItem(str(item)))
                    column += 1

                
                row_position = self.tableWidget_7.rowCount()
                self.tableWidget_7.insertRow(row_position)


 ###########Carburant 

    def Add_carburant(self):
        type_carburant= self.carburant.text()
        carburant_id = self.carburantid.text()
        add_carburant = Carburants(carburant_id,type_carburant)
        add = add_carburant.AddCr()
        self.carburantid.setText('')
        self.carburant.setText('')
        self.Show_carburant()


    
    def Edit_carburant(self):
        type_carburant= self.carburant.text()
        carburant_id = self.carburantid.text()
        add_carburant = Carburants(carburant_id,type_carburant)
        add = add_carburant.AddCr()
        self.carburant.setText('')
        self.carburantid.setText('')
        self.Show_carburant()

    
    def Delete_carburant(self):

        type_carburant= self.carburant.text()
        carburant_id = self.carburantid.text()
        delete_carburant = Carburants(carburant_id,type_carburant)
        delete = delete_carburant.DeleteCr()
        self.carburantid.setText('')
        self.Show_carburant()



    def Show_carburant(self):
        self.db = MySQLdb.connect(host='localhost' ,user='root' ,password='Houssam@2002' ,db='carrental')
        self.cur= self.db.cursor()
        self.cur.execute('''SELECT idC, carburant from carburant ''')
        data = self.cur.fetchall()


        if data :
            self.tableWidget_3.setRowCount(0)
            self.tableWidget_3.insertRow(0)
            for row , form in enumerate(data) :
                for column , item in enumerate(form) :
                    self.tableWidget_3.setItem(row , column , QTableWidgetItem(str(item)))
                    column += 1

                
                row_position = self.tableWidget_3.rowCount()
                self.tableWidget_3.insertRow(row_position)


    ##############################################
        #######show data to comboboxes ###########################

    def Show_categorie_cmb(self) :
        self.db = MySQLdb.connect(host='localhost' ,user='root' ,password='Houssam@2002' ,db='carrental')
        self.cur= self.db.cursor()
        self.cur.execute('''SELECT Cname from categorie''')
        data = self.cur.fetchall()
        
        for categorie in data:
             self.categorieCMB.addItem(categorie[0])
             self.editcategorieC.addItem(categorie[0])
             

    def Show_carburant_cmb(self):
        self.db = MySQLdb.connect(host='localhost' ,user='root' ,password='Houssam@2002' ,db='carrental')
        self.cur= self.db.cursor()
        self.cur.execute('''SELECT carburant from carburant''')
        data = self.cur.fetchall()
        
        for typec in data:
             self.carburantCMB.addItem(typec[0])
             self.editcarburantc.addItem(typec[0])

    def Show_disponibiliter_cmb(self):
        
        self.db = MySQLdb.connect(host='localhost' ,user='root' ,password='Houssam@2002' ,db='carrental')
        self.cur= self.db.cursor()
        self.cur.execute('''SELECT disponibilite from disponibilite''')
        data = self.cur.fetchall()
        
        for dispo in data:
             self.dispoCMB.addItem(dispo[0])
             self.comboBox.addItem(dispo[0])
             self.editdispoC.addItem(dispo[0])

    def Show_transmition_cmb(self):
        self.db = MySQLdb.connect(host='localhost' ,user='root' ,password='Houssam@2002' ,db='carrental')
        self.cur= self.db.cursor()
        self.cur.execute('''SELECT typeTransmition from transmition''')
        data = self.cur.fetchall()
        
        for trans in data:
             self.transmitionCMB.addItem(trans[0])
             self.edittransmitionC.addItem(trans[0])

    
#def main():
    #app = QApplication(sys.argv) #this qapplication consists of many qwidgets
    #window = Ui_MainWindow()
    #window.show()
    #app.exec_()

    #Main = QtWidgets.QMainWindow()
    #ui=Ui_Form()
    #ui.setupUi(Main) 
    #Main.show()
    #app.exec_()
    #ui.logbtn.clicked.connect(ui.connect)
    
#if __name__ == '__main__':
    #main()



if __name__ == "__main__":
    
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    uYi = Ui_MainWindow()
    uYi.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
