# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import res, sys
from AdmindPage import Ui_MainWindow
from UserInetface import Ui_MainWindo
from AdmindPage import *
from UserInetface import *
import MySQLdb



class Ui_login(object):
    def setupUi(self, login):
        login.setObjectName("login")
        login.resize(682, 677)
        self.widget = QtWidgets.QWidget(login)
        self.widget.setGeometry(QtCore.QRect(30, 30, 621, 631))
        self.widget.setStyleSheet("QPushButton#pushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477,stop:0 rgba(11,131,120,219),stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#pushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));}\n"
"QPushButton#pushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"background-color:rgba(150, 123, 111,255);}\n"
"")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(19, 30, 301, 571))
        self.label.setStyleSheet("\n"
"border-image: url(:/pics/pics/kl.jpg);\n"
"border-top-left-radius:50px;\n"
"border-bottom-right-radius:50px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 281, 571))
        self.label_2.setStyleSheet("\n"
"background-color:rgba(0,0,0,80);\n"
"border-top-left-radius:50px;\n"
"border-bottom-right-radius:50px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(270, 20, 331, 571))
        self.label_3.setStyleSheet("background-color:rgba(255,255,255,255);\n"
"border-bottom-right-radius: 50px;\n"
"border-top-left-radius: 50px;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(370, 100, 111, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgba(0,0,0,200);")
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setGeometry(QtCore.QRect(300, 220, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom: 7px;")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setGeometry(QtCore.QRect(300, 310, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom: 7px;")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(330, 440, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.connect)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(19, 80, 251, 130))
        self.label_5.setStyleSheet("background-color:rgba(0,0,0,75);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(20, 80, 211, 40))
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:rgba(255,255,255,210);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(30, 130, 220, 50))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color:rgba(255,255,255,200);")
        self.label_7.setObjectName("label_7")
        self.error = QtWidgets.QLabel(self.widget)
        self.error.setGeometry(QtCore.QRect(330, 520, 201, 20))
        self.error.setText("")
        self.error.setObjectName("error")

        self.retranslateUi(login)
        QtCore.QMetaObject.connectSlotsByName(login)

    def retranslateUi(self, login):
        _translate = QtCore.QCoreApplication.translate
        login.setWindowTitle(_translate("login", "Form"))
        self.label_4.setText(_translate("login", "Log In"))
        self.lineEdit.setPlaceholderText(_translate("login", " user name"))
        self.lineEdit_2.setPlaceholderText(_translate("login", " password"))
        self.pushButton.setText(_translate("login", "Log In"))
        self.label_6.setText(_translate("login", "Cars RENTAL"))
        self.label_7.setText(_translate("login", "Hi,\n"
" Welcome back.\n"
" Ihope we got some new bookings."))
   
    def con(self):
                
                name = self.lineEdit.text().lower()
                if name=="admin":
                        log = QtWidgets.QWidget()
                        u = Ui_login()
                        u.setupUi(log)
                        log.close()
                        self.lineEdit.setText('')
                        self.lineEdit_2.setText('')
                        self.client = QtWidgets.QMainWindow()
                        self.ui=Ui_MainWindow()
                        self.ui.setupUi(self.client) 
                        self.client.show()
                else:
                        logA = QtWidgets.QWidget()
                        ui = Ui_login()
                        ui.setupUi(logA)
                        logA.close()
                        self.lineEdit.setText('')
                        self.lineEdit_2.setText('')
                        self.Principe = QtWidgets.QMainWindow()
                        self.uui=Ui_MainWindo()
                        self.uui.setupUi(self.Principe) 
                        self.Principe.show()
                
    def connect(self):
        self.db = MySQLdb.connect(host='localhost' ,user='root' ,password='Houssam@2002' ,db='carrental')
        self.cur= self.db.cursor()
        name = self.lineEdit.text().lower()
        password = self.lineEdit_2.text()
        self.cur.execute('''SELECT nomp, email, password from users where nomP like (%s) and password like (%s)''', (name, password))
        data = self.cur.fetchone()
        

        if len(name)==0:
            self.error.setText("Input Username is empty!!")
            if len(password)==0:
             self.error.setText("Input password is empty!!")
        elif data == None:
                self.error.setText("incorrect password or name")
                self.lineEdit.setText('')
                self.lineEdit_2.setText('')
        
        else: 
              self.con()
        
        
        
             
                
if __name__ == "__main__":
        app = QtWidgets.QApplication(sys.argv)
        login = QtWidgets.QWidget()
        ui = Ui_login()
        ui.setupUi(login)
        login.show()
        sys.exit(app.exec_())