# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'No.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from PyQt5.QtGui import QPixmap
import sys 
import MySQLdb
import icons_rc
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindo(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1607, 652)
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("\n"
"\n"
"#centralwidget{\n"
"    background-color: #FFF5EE;\n"
"}\n"
"#tab{\n"
"color: white;\n"
"background-color:#FFF5EE;\n"
"}\n"
"#tab_2{\n"
"background-color:#FFF5EE;\n"
"}\n"
"#opBtn, #carBtn, #setBtn, #usrBtn{\n"
"border: 5px solid  #539CFF;\n"
"background-color:;\n"
"border-radius: 19px;\n"
"}\n"
"#opBtn:pressed{\n"
"    background-color: #539CFF;\n"
" }\n"
"#carBtn:pressed{\n"
"    background-color: #539CFF;\n"
" }\n"
"#setBtn:pressed{\n"
"    background-color: #539CFF;\n"
" }\n"
"#usrBtn:pressed{\n"
"    background-color: #539CFF;\n"
"  }\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.opBtn = QtWidgets.QPushButton(self.centralwidget)
        self.opBtn.setGeometry(QtCore.QRect(40, 140, 93, 81))
        self.opBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/dd.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.opBtn.setIcon(icon)
        self.opBtn.setIconSize(QtCore.QSize(60, 70))
        self.opBtn.setObjectName("opBtn")
        self.carBtn = QtWidgets.QPushButton(self.centralwidget)
        self.carBtn.setGeometry(QtCore.QRect(40, 270, 93, 81))
        self.carBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/mn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.carBtn.setIcon(icon1)
        self.carBtn.setIconSize(QtCore.QSize(60, 60))
        self.carBtn.setObjectName("carBtn")
        self.usrBtn = QtWidgets.QPushButton(self.centralwidget)
        self.usrBtn.setGeometry(QtCore.QRect(40, 400, 93, 81))
        self.usrBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/prs.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.usrBtn.setIcon(icon2)
        self.usrBtn.setIconSize(QtCore.QSize(60, 60))
        self.usrBtn.setObjectName("usrBtn")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(160, 10, 1451, 761))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(11)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("QPushButton#addOpBtn{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477,stop:0 rgba(0,131,120,219),stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#addOpBtn:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));}\n"
"QPushButton#addOpBtn:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"background-color:rgba(150, 123, 111,255);}\n"
"\n"
"\n"
"QPushButton#delOpBtn{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477,stop:0 rgba(150, 123, 111, 219),stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#delOpBtn:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111,255), stop:1 rgba(85, 81, 84, 226));}\n"
"QPushButton#delOpBtn:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"background-color:rgba(150, 123, 111,255);}\n"
"\n"
"QPushButton#updOpBtn{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477,stop:0 rgb(0, 156, 208),stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#updOpBtn:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111,255), stop:1 rgba(85, 81, 84, 226));}\n"
"QPushButton#updOpBtn:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"background-color:rgba(150, 123, 111,255);}\n"
"\n"
"QPushButton#addcBtn{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477,stop:0 rgba(0,131,120,219),stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#addcBtn:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));}\n"
"QPushButton#addcBtn:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"background-color:rgba(150, 123, 111,255);}\n"
"\n"
"QPushButton#delcBtn{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477,stop:0 rgba(150, 123, 111, 219),stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#delcBtn:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111,255), stop:1 rgba(85, 81, 84, 226));}\n"
"QPushButton#delcBtn:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"background-color:rgba(150, 123, 111,255);}\n"
"\n"
"QPushButton#editcBtn{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477,stop:0 rgb(0, 156, 208),stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#editcBtn:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111,255), stop:1 rgba(85, 81, 84, 226));}\n"
"QPushButton#editcBtn:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"background-color:rgba(150, 123, 111,255);}\n"
"\n"
"QPushButton#adduser{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477,stop:0 rgba(0,131,120,219),stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#adduser:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));}\n"
"QPushButton#adduser:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"background-color:rgba(150, 123, 111,255);}\n"
"\n"
"QPushButton#deluser{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477,stop:0 rgba(150, 123, 111, 219),stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#deluser:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111,255), stop:1 rgba(85, 81, 84, 226));}\n"
"QPushButton#deluser:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"background-color:rgba(150, 123, 111,255);}\n"
"\n"
"QPushButton#edituser{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477,stop:0 rgb(0, 156, 208),stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#edituser:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111,255), stop:1 rgba(85, 81, 84, 226));}\n"
"QPushButton#edituser:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"background-color:rgba(150, 123, 111,255);}\n"
"\n"
"\n"
"\n"
"QPushButton#addcatBtn{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477,stop:0 rgba(0,131,120,219),stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#addcatBtn:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));}\n"
"QPushButton#addcatBtn:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"background-color:rgba(150, 123, 111,255);}\n"
"\n"
"QPushButton#delcat{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477,stop:0 rgba(150, 123, 111, 219),stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#delcat:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111,255), stop:1 rgba(85, 81, 84, 226));}\n"
"QPushButton#delcat:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"background-color:rgba(150, 123, 111,255);}\n"
"\n"
"QPushButton#editcatB{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477,stop:0 rgb(0, 156, 208),stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#editcatB:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111,255), stop:1 rgba(85, 81, 84, 226));}\n"
"QPushButton#editcatB:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"background-color:rgba(150, 123, 111,255);}\n"
"\n"
"\n"
"\n"
"\n"
"QPushButton#addt{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477,stop:0 rgba(0,131,120,219),stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#addt:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));}\n"
"QPushButton#addt:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"background-color:rgba(150, 123, 111,255);}\n"
"QPushButton#delt{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477,stop:0 rgba(150, 123, 111, 219),stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#delt:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111,255), stop:1 rgba(85, 81, 84, 226));}\n"
"QPushButton#delt:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"background-color:rgba(150, 123, 111,255);}\n"
"\n"
"QPushButton#editt{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477,stop:0 rgb(0, 156, 208),stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#editt:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111,255), stop:1 rgba(85, 81, 84, 226));}\n"
"QPushButton#editt:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"background-color:rgba(150, 123, 111,255);}\n"
"\n"
"\n"
"\n"
"QPushButton#addcarb{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477,stop:0 rgba(0,131,120,219),stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#addcarb:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));}\n"
"QPushButton#addcarb:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"background-color:rgba(150, 123, 111,255);}\n"
"QPushButton#delcarb{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477,stop:0 rgba(150, 123, 111, 219),stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#delcarb:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111,255), stop:1 rgba(85, 81, 84, 226));}\n"
"QPushButton#delcarb:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"background-color:rgba(150, 123, 111,255);}\n"
"\n"
"QPushButton#editcarb{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477,stop:0 rgb(0, 156, 208),stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#searchbtnhover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111,255), stop:1 rgba(85, 81, 84, 226));}\n"
"QPushButton#searchbtn:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"background-color:rgba(150, 123, 111,255);}\n"
"\n"
"\n"
"QPushButton#searchbtn{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477,stop:0 rgb(0, 156, 208),stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#editcarb:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111,255), stop:1 rgba(85, 81, 84, 226));}\n"
"QPushButton#editcarb:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"background-color:rgba(150, 123, 111,255);}")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(180, 60, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.searchCMB = QtWidgets.QComboBox(self.tab_2)
        self.searchCMB.setGeometry(QtCore.QRect(320, 50, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.searchCMB.setFont(font)
        self.searchCMB.setObjectName("searchCMB")
        self.searchCMB.addItem("")
        self.searchCMB.addItem("")
        self.searchCMB.addItem("")
        self.searchCMB.addItem("")
        self.searchCMB.addItem("")
        self.label_35 = QtWidgets.QLabel(self.tab_2)
        self.label_35.setGeometry(QtCore.QRect(460, 10, 601, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.searchbtn = QtWidgets.QPushButton(self.tab_2)
        self.searchbtn.setGeometry(QtCore.QRect(920, 60, 171, 51))
        self.searchbtn.setObjectName("searchbtn")
        self.searchtxt = QtWidgets.QLineEdit(self.tab_2)
        self.searchtxt.setGeometry(QtCore.QRect(870, 10, 271, 31))
        self.searchtxt.setObjectName("searchtxt")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_4.setGeometry(QtCore.QRect(0, 140, 1451, 501))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tableWidget_4.setFont(font)
        self.tableWidget_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableWidget_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget_4.setLineWidth(2)
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(10)
        self.tableWidget_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(9, item)
        self.tableWidget_4.verticalHeader().setVisible(False)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setGeometry(QtCore.QRect(0, 140, 1451, 511))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(11)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 255, 255))
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        self.tableWidget.verticalHeader().setVisible(False)
        self.addOpBtn = QtWidgets.QPushButton(self.tab)
        self.addOpBtn.setGeometry(QtCore.QRect(1040, 40, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.addOpBtn.setFont(font)
        self.addOpBtn.setObjectName("addOpBtn")
        self.idtxt = QtWidgets.QLineEdit(self.tab)
        self.idtxt.setGeometry(QtCore.QRect(310, 50, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.idtxt.setFont(font)
        self.idtxt.setObjectName("idtxt")
        self.nbdateCMB = QtWidgets.QComboBox(self.tab)
        self.nbdateCMB.setGeometry(QtCore.QRect(680, 50, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.nbdateCMB.setFont(font)
        self.nbdateCMB.setObjectName("nbdateCMB")
        self.nbdateCMB.addItem("")
        self.nbdateCMB.addItem("")
        self.nbdateCMB.addItem("")
        self.nbdateCMB.addItem("")
        self.nbdateCMB.addItem("")
        self.nbdateCMB.addItem("")
        self.nbdateCMB.addItem("")
        self.nbdateCMB.addItem("")
        self.nbdateCMB.addItem("")
        self.nbdateCMB.addItem("")
        self.nbdateCMB.addItem("")
        self.nbdateCMB.addItem("")
        self.nbdateCMB.addItem("")
        self.nbdateCMB.addItem("")
        self.nbdateCMB.addItem("")
        self.nbdateCMB.addItem("")
        self.nbdateCMB.addItem("")
        self.nbdateCMB.addItem("")
        self.nbdateCMB.addItem("")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(610, 50, 55, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_33 = QtWidgets.QLabel(self.tab)
        self.label_33.setGeometry(QtCore.QRect(160, 50, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.tab)
        self.label_34.setGeometry(QtCore.QRect(0, 0, 731, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_2.setGeometry(QtCore.QRect(430, 30, 491, 491))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.newname = QtWidgets.QLineEdit(self.groupBox_2)
        self.newname.setGeometry(QtCore.QRect(200, 180, 231, 31))
        self.newname.setObjectName("newname")
        self.confpass = QtWidgets.QLineEdit(self.groupBox_2)
        self.confpass.setGeometry(QtCore.QRect(200, 330, 231, 31))
        self.confpass.setText("")
        self.confpass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confpass.setObjectName("confpass")
        self.label_26 = QtWidgets.QLabel(self.groupBox_2)
        self.label_26.setGeometry(QtCore.QRect(30, 230, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.newpass = QtWidgets.QLineEdit(self.groupBox_2)
        self.newpass.setGeometry(QtCore.QRect(200, 280, 231, 31))
        self.newpass.setText("")
        self.newpass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.newpass.setObjectName("newpass")
        self.edituser = QtWidgets.QPushButton(self.groupBox_2)
        self.edituser.setGeometry(QtCore.QRect(170, 400, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.edituser.setFont(font)
        self.edituser.setObjectName("edituser")
        self.label_27 = QtWidgets.QLabel(self.groupBox_2)
        self.label_27.setGeometry(QtCore.QRect(30, 180, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.groupBox_2)
        self.label_28.setGeometry(QtCore.QRect(30, 330, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.newemail = QtWidgets.QLineEdit(self.groupBox_2)
        self.newemail.setGeometry(QtCore.QRect(200, 230, 231, 31))
        self.newemail.setObjectName("newemail")
        self.label_25 = QtWidgets.QLabel(self.groupBox_2)
        self.label_25.setGeometry(QtCore.QRect(30, 280, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.oldname = QtWidgets.QLineEdit(self.groupBox_2)
        self.oldname.setGeometry(QtCore.QRect(200, 110, 231, 31))
        self.oldname.setObjectName("oldname")
        self.label_41 = QtWidgets.QLabel(self.groupBox_2)
        self.label_41.setGeometry(QtCore.QRect(30, 120, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.tabWidget.addTab(self.tab_3, "")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 230, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 360, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 490, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1607, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Search car by:"))
        self.searchCMB.setItemText(0, _translate("MainWindow", "Marque"))
        self.searchCMB.setItemText(1, _translate("MainWindow", "Type de Carburant"))
        self.searchCMB.setItemText(2, _translate("MainWindow", "Nombre du Place"))
        self.searchCMB.setItemText(3, _translate("MainWindow", "Prix par jour"))
        self.searchCMB.setItemText(4, _translate("MainWindow", "Transmition"))
        self.label_35.setText(_translate("MainWindow", "search for the car you want and remember its id"))
        self.searchbtn.setText(_translate("MainWindow", "Search"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Image"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Marque"))
        item = self.tableWidget_4.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Modele"))
        item = self.tableWidget_4.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Categorie"))
        item = self.tableWidget_4.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Type carburant"))
        item = self.tableWidget_4.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Nombre Place"))
        item = self.tableWidget_4.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Transmition"))
        item = self.tableWidget_4.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Prix"))
        item = self.tableWidget_4.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Disponibilite"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Search a Car"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Image"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Marque"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Model"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Categorie"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "TypeCarburant"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "NombrePlace"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Transmission"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "PrixParJour"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "dateReservation"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "dateLimite"))
        self.addOpBtn.setText(_translate("MainWindow", "Add"))
        self.nbdateCMB.setItemText(0, _translate("MainWindow", "1"))
        self.nbdateCMB.setItemText(1, _translate("MainWindow", "2"))
        self.nbdateCMB.setItemText(2, _translate("MainWindow", "3"))
        self.nbdateCMB.setItemText(3, _translate("MainWindow", "4"))
        self.nbdateCMB.setItemText(4, _translate("MainWindow", "5"))
        self.nbdateCMB.setItemText(5, _translate("MainWindow", "6"))
        self.nbdateCMB.setItemText(6, _translate("MainWindow", "7"))
        self.nbdateCMB.setItemText(7, _translate("MainWindow", "8"))
        self.nbdateCMB.setItemText(8, _translate("MainWindow", "9"))
        self.nbdateCMB.setItemText(9, _translate("MainWindow", "10"))
        self.nbdateCMB.setItemText(10, _translate("MainWindow", "11"))
        self.nbdateCMB.setItemText(11, _translate("MainWindow", "12"))
        self.nbdateCMB.setItemText(12, _translate("MainWindow", "13"))
        self.nbdateCMB.setItemText(13, _translate("MainWindow", "14"))
        self.nbdateCMB.setItemText(14, _translate("MainWindow", "15"))
        self.nbdateCMB.setItemText(15, _translate("MainWindow", "16"))
        self.nbdateCMB.setItemText(16, _translate("MainWindow", "17"))
        self.nbdateCMB.setItemText(17, _translate("MainWindow", "18"))
        self.nbdateCMB.setItemText(18, _translate("MainWindow", "19"))
        self.label_2.setText(_translate("MainWindow", "Days"))
        self.label_33.setText(_translate("MainWindow", "Id of the element"))
        self.label_34.setText(_translate("MainWindow", "Add the car\'s id and the how many days u want to rent it "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Rent a Car"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Edit you information"))
        self.label_26.setText(_translate("MainWindow", "email"))
        self.edituser.setText(_translate("MainWindow", "Edit my info"))
        self.label_27.setText(_translate("MainWindow", "new name"))
        self.label_28.setText(_translate("MainWindow", "confirm password"))
        self.label_25.setText(_translate("MainWindow", "password"))
        self.label_41.setText(_translate("MainWindow", "old name"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Edit ur account"))
        self.label.setText(_translate("MainWindow", "Search a Car"))
        self.label_4.setText(_translate("MainWindow", "Rent a Car"))
        self.label_5.setText(_translate("MainWindow", "Edit Info"))

        self.Handel_Buttons()
        self.Handel_UI_Changes()
        self.Show_car()
        self.Show_Opcar()
        



    def Handel_UI_Changes(self):
        self.tabWidget.tabBar().setVisible(False)

    def Handel_Buttons(self):
        self.searchbtn.clicked.connect(self.Search_car)
        self.addOpBtn.clicked.connect(self.Add_carOp)
        self.carBtn.clicked.connect(self.cars_show)
        self.opBtn.clicked.connect(self.operations_show)
        self.usrBtn.clicked.connect(self.user_show)
        self.edituser.clicked.connect(self.Edit_user)
        

    def operations_show(self):
         self.tabWidget.setCurrentIndex(0)

    def cars_show(self):
         self.tabWidget.setCurrentIndex(1)

    def user_show(self):
         self.tabWidget.setCurrentIndex(2)

    def settings_show(self):
         self.tabWidget.setCurrentIndex(3)   



    def Show_Opcar(self):
        #ui = Ui_login()
        #client = ui.Cuser()
        self.db = MySQLdb.connect(host='localhost' ,user='root' ,password='Houssam@2002' ,db='carrental')
        self.cur= self.db.cursor()
        self.cur.execute('''SELECT idC, image, marque, modele,  categorie, typeCarburant, nombrePlace, transmition, prixJour, dateReserv, dateRetrieve from car where Disponibilite = "Non Disponible"''')
        data = self.cur.fetchall()


        if data :
            self.tableWidget.setRowCount(0)
            self.tableWidget.insertRow(0)
            for row , form in enumerate(data) :
                for column , item in enumerate(form) :
                
                    if (column == 1):
                        pixmap = QPixmap()
                        pixmap.loadFromData(item)
                        QTableWidgetItem(str(item)).setIcon(QIcon(pixmap))
                    else:   
                        self.tableWidget.setItem(row , column , QTableWidgetItem(str(item)))
                        column += 1

                
                row_position = self.tableWidget.rowCount()
                self.tableWidget.insertRow(row_position) 

    def Show_car(self):
        self.db = MySQLdb.connect(host='localhost' ,user='root' ,password='Houssam@2002' ,db='carrental')
        self.cur= self.db.cursor()
        self.cur.execute('''SELECT idC, image, marque, modele,  categorie, typeCarburant, nombrePlace, transmition, prixJour, Disponibilite from car ''')
        data = self.cur.fetchall()


        if data :
            self.tableWidget_4.setRowCount(0)
            self.tableWidget_4.insertRow(0)
            for row , form in enumerate(data) :
                for column , item in enumerate(form) :
                
                    if (column == 1):
                        pixmap = QPixmap()
                        pixmap.loadFromData(item)
                        QTableWidgetItem(str(item)).setIcon(QIcon(pixmap))
                    else:   
                        self.tableWidget_4.setItem(row , column , QTableWidgetItem(str(item)))
                        column += 1

                
                row_position = self.tableWidget_4.rowCount()
                self.tableWidget_4.insertRow(row_position)
    def getImageLabel(self,image):
                imageLabel = QLabel(self.centralwidget)
                imageLabel.setText("")
                imageLabel.setScaledContents(True)
                pixmap = QPixmap()
                pixmap.loadFromData(image,'jpg')
                imageLabel.setPixmap(pixmap)
                return imageLabel
    

    def Search_car(self):
        self.db = MySQLdb.connect(host='localhost' ,user='root' ,password='Houssam@2002' ,db='carrental')
        self.cur= self.db.cursor()
        search = self.searchtxt.text()
        searchBy = self.searchCMB.currentText()
        if(searchBy == 'Marque'):
            self.cur.execute('''SELECT idC, image, marque, modele,  categorie, typeCarburant, nombrePlace, transmition, prixJour, Disponibilite from car where marque = (%s)''',(search,))
            
        if(searchBy == 'Type du Carburant'):
            self.cur.execute('''SELECT idC, image, marque, modele,  categorie, typeCarburant, nombrePlace, transmition, prixJour, Disponibilite from car  where typeCarburant = (%s)''',(search,))
           
        if(searchBy == 'Nombre du Place'):
            self.cur.execute('''SELECT idC, image, marque, modele,  categorie, typeCarburant, nombrePlace, transmition, prixJour, Disponibilite from car  where nombrePlace = (%s)''',(search,))
            
        if(searchBy == 'Prix par jour'):
            self.cur.execute('''SELECT idC, image, marque, modele,  categorie, typeCarburant, nombrePlace, transmition, prixJour, Disponibilite from car  where prixJour = (%s)''',(search,))
            
        if(searchBy == 'Transmition'):
            self.cur.execute('''SELECT idC, image, marque, modele,  categorie, typeCarburant, nombrePlace, transmition, prixJour, Disponibilite from car  where transmition = (%s)''',(search,))
            
        data = self.cur.fetchall()
        if data :
            self.tableWidget_4.setRowCount(0)
            self.tableWidget_4.insertRow(0)
            for row , form in enumerate(data) :
                for column , item in enumerate(form) :
                    it = str(item)
                    if (column == 1):
                        it=self.getImageLabel(item)
                        self.tableWidget_4.setCellWidget(row, column, it)
                    else:   
                        self.tableWidget_4.setItem(row , column , QTableWidgetItem(str(item)))
                        column += 1

                
                row_position = self.tableWidget_4.rowCount()
                self.tableWidget_4.insertRow(row_position)
    def getImageLabel(self,image):
                imageLabel = QLabel(self.centralwidget)
                imageLabel.setText("")
                imageLabel.setScaledContents(True)
                pixmap = QPixmap()
                pixmap.loadFromData(image,'jpg')
                imageLabel.setPixmap(pixmap)
                return imageLabel
    
    def Add_carOp(self):

        self.db = MySQLdb.connect(host='localhost' ,user='root' ,password='Houssam@2002' ,db='carrental')
        self.cur= self.db.cursor()
        car_id = self.idtxt.text()
        car_date = self.nbdateCMB.currentText()
        self.cur.execute('''UPDATE car SET Disponibilite = "Non disponible", dateReserv = CURDATE(), dateRetrieve = DATE_ADD(CURDATE(), INTERVAL (%s) DAY) WHERE idC = (%s)''', (car_date, car_id,))

        self.db.commit()
        
        #addCarOP = Cars(car_id, '', '', '', '', '', '', '', '','', car_dispoCHange,car_date)
        #add = addCarOP.AddCO()
        self.idtxt.setText('')
        self.Show_Opcar()
        self.Show_car()

    def Edit_user(self):
        self.db = MySQLdb.connect(host='localhost' ,user='root' ,password='Houssam@2002' ,db='carrental')
        self.cur= self.db.cursor()
        Oname = self.oldname.text()
        Uname = self.newname.text()
        email = self.newemail.text()
        password = self.newpass.text()
        cpass = self.confpass.text()
        self.cur.execute('''update users set nomP = (%s), email = (%s), password = (%s) where nomP = (%s)
            ''', (Uname, email, password, Oname))

       
        
        
        if password == cpass:
            #editUser=Users(Oname, email, password, Uname)
            #edit=editUser.EditU()
            self.db.commit()
            #self.error.setText("user "+Uname+" was updated succefuly")
            self.oldname.setText('')
            self.newname.setText('')
            self.newemail.setText('')
            self.newpass.setText('')
            self.confpass.setText('')
        else:
            self.error.setText("the password does not match")
            self.confpass.setText('')
            self.newpass.setText('')

if __name__ == "__main__":
    
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    uYi = Ui_MainWindo()
    uYi.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

